apiVersion: v1
kind: Namespace
metadata:
  name: spire
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: spire
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: spire
  labels:
    app: db
spec:
  containers:
    - name: db
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
  volumes:
    - name: nginx-config
      configMap:
        name: db-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: spire
data:
  nginx.conf: |
    server {
        listen 1111;
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            return 200 "db response";
        }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: vault
  namespace: spire
  labels:
    app: vault
spec:
  containers:
    - name: vault
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
  volumes:
    - name: nginx-config
      configMap:
        name: vault-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: spire
data:
  nginx.conf: |
    server {
        listen 9999;
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            return 200 "vault response";
        }
    }
