# create role and rolebinding for all verb for deploy
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-all
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-deploy
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deploy-all
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
